# This file created by conda-build 3.20.4
# meta.yaml template originally from:
# /tmp/build/80754af9/combined_recipe, last modified Wed Oct 14 16:27:15 2020
# ------------------------------------------------

package:
    name: xlsxwriter
    version: 1.3.7
source:
    fn: XlsxWriter-1.3.7.tar.gz
    sha256: 9b1ade2d1ba5d9b40a6d1de1d55ded4394ab8002718092ae80a08532c2add2e6
    url: https://pypi.io/packages/source/X/XlsxWriter/XlsxWriter-1.3.7.tar.gz
build:
    noarch: python
    number: '0'
    script: /tmp/build/80754af9/xlsxwriter_1602692860603/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/python
        -m pip install . --no-deps -vv
    string: py_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.10.14 0
        - certifi 2020.6.20 py36_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20191231 h14c3975_1
        - libffi 3.3 he6710b0_2
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1h h7b6447c_0
        - pip 20.2.3 py36_0
        - python 3.6.12 hcff3b4d_2
        - readline 8.0 h7b6447c_0
        - setuptools 50.3.0 py36hb0f4dca_1
        - sqlite 3.33.0 h62c20be_0
        - tk 8.6.10 hbc83047_0
        - wheel 0.35.1 py_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - python
test:
    imports:
        - xlsxwriter
about:
    description: 'XlsxWriter is a Python module that can be used to write text, numbers,
        formulas

        and hyperlinks to multiple worksheets in an Excel 2007+ XLSX file.

        '
    dev_url: https://github.com/jmcnamara/XlsxWriter
    doc_source_url: https://github.com/jmcnamara/XlsxWriter/blob/master/docs/XlsxWriter.pdf
    doc_url: https://xlsxwriter.readthedocs.org/
    home: https://xlsxwriter.readthedocs.io/
    license: BSD-2-Clause
    license_family: BSD
    license_file: LICENSE.txt
    summary: A Python module for creating Excel XLSX files
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - mcs07
        - nehaljwani
